sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 10

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tNcYLHCKMQqtZKqa8M8
    access-key-secret: 1YYPEYuW1v6McudcnGVzU5aMUe0uzq
    bucket-name: yyue-course